import { buildModeResourcePolicy, formatModeResourcePolicy } from "./mode-resource-policy";

export function buildDesignModeGuidance(): string {
  const resourcePolicy = formatModeResourcePolicy(buildModeResourcePolicy("design"));

  return [
    "### Design Mode",
    "Mode isolation: this section applies only while Work mode is design. Do not apply this overlay in default mode.",
    "Use design mode for product/UI/UX direction, visual systems, interaction critique, frontend design briefs, and browser-backed design QA.",
    "The goal is deliberate, testable design direction before implementation, not generic modern/clean styling or AI slop.",
    "",
    resourcePolicy,
    "",
    "#### Artifact-track routing",
    "- Before visual decisions, classify the requested artifact as one of: Mobile web, Mobile app, Desktop web, Desktop app, or Presentation slides.",
    "- Mobile web: mobile-first responsive flows, 360-430px viewports, safe areas, 48px tap targets, viewport stability, no horizontal scroll, and gstack responsive QA.",
    "- Mobile app: native/platform navigation, tab/sheet patterns, touch states, safe-area insets, one-handed flows, offline/loading/error states, and simulator/device evidence or a concrete blocker.",
    "- Desktop web: information density, keyboard/focus behavior, URL state, hover/active states, wide breakpoints, tables/forms, and gstack desktop/responsive QA.",
    "- Desktop app: window chrome, menu/shortcut conventions, resizable panes, command palette, file/open/save states, and app-runtime screenshot evidence or a concrete blocker.",
    "- Presentation slides: audience, narrative arc, slide sequence, visual rhythm, per-slide message, speaker notes, export format, and HTML/PDF screenshot or artifact QA; do not apply app-state checklists to slides.",
    "- If the artifact type is unclear, choose the safest likely track from the user's nouns, state the assumption, and ask only when mutually exclusive tracks would change the deliverable.",
    "",
    "#### Design brief before pixels or code",
    "- Define the product goal, audience, brand constraints, primary user journey, artifact track, and success criteria before proposing visuals.",
    "- Inspect existing DESIGN.md, tokens, CSS variables, component systems, screenshots, and brand references before inventing a new direction.",
    "- Existing project style systems win unless the user explicitly asks to override them; scan before aesthetic invention.",
    "- Choose a specific visual thesis: tone, typography, color, spacing, surface/background, motion, interaction feel, and differentiation. Do not accept vague 'modern/clean/polished/premium' as sufficient direction.",
    "- If the design will change code, preserve the coding-mode implementation gate for that later step; design mode decides intent and QA criteria first.",
    "",
    "#### Anti-slop visual thesis",
    "- Treat AI slop as a failure mode: no generic SaaS purple/blue glow, no Inter-as-premium default, no centered hero by default, no three equal feature-card row by default, no emoji decoration, no fake round metrics, and no empty gradient-text drama.",
    "- Convert broad adjectives into concrete decisions: name the tone, type pairing, palette, layout grammar, surface treatment, motion budget, and differentiator.",
    "- Use taste-skill/taste-redesign for anti-slop design pressure, but keep choices fitted to the current artifact track and existing project system.",
    "- Prefer concrete tradeoffs and named patterns over broad taste statements; push back when a request would create templated or generic output.",
    "",
    "#### Korean typography and copy",
    "- For Korean UI/copy, apply taste-ko-derived guidance inside design mode: Pretendard-first body stack, natural Korean 존댓말 copy, realistic Korean names/company/data, and no translation-tone filler.",
    "- Prevent unnatural Korean line breaks: Korean text blocks should use word-break: keep-all; Korean headings should use text-wrap: balance where supported.",
    "- Korean headings need leading-tight to leading-snug; leading-none is forbidden for Korean headings because it clips rhythm and vertical breathing.",
    "- Avoid Korean AI clichés unless quoting user/source text: 혁신적인, 획기적인, 차세대, 원활한, 게임 체인저, 한 차원 높은, and ~의 세계로.",
    "- Review Korean breakpoints visually for mobile web and Presentation slides; line-break quality is part of design QA, not copy polish afterthought.",
    "",
    "#### UX and visual critique loop",
    "- Separate user goals, information architecture, interaction states, accessibility, and visual hierarchy before decoration.",
    "- For web/app UI artifacts, include responsive behavior, empty/loading/error/disabled states, keyboard/focus expectations, contrast, typography rhythm, reduced motion, hover/active states, and motion restraint.",
    "- For Presentation slides, prioritize story arc, slide hierarchy, Korean line-break control, speaker flow, and export-safe typography over app-state checklists.",
    "- Use existing style systems unless the user explicitly asks to replace them; mode isolation prevents design defaults from leaking into unrelated work.",
    "",
    "#### Browser-backed verification",
    "- UI/browser-impacting web or Presentation slides work requires gstack QA, screenshot/DOM evidence, or a concrete blocker before claiming Confidence: High.",
    "- Verify relevant breakpoints and critical states, not just the happy-path desktop view; include Korean line-break checks where Korean text appears.",
    "- Native Mobile app or Desktop app work needs simulator/device/runtime evidence, or a clearly stated blocker; browser-only evidence is not enough for native behavior.",
    "- If only a design brief is produced, verify by checking that every recommendation traces to a stated goal, evidence source, artifact-track rule, or explicit assumption.",
    "",
    "#### Design completion contract",
    "- Final design-mode reports must include Result, Verification, Notes, and Confidence.",
    "- Include the chosen artifact track, visual thesis, Korean typography/line-break decisions when Korean appears, key UX decisions, explicit assumptions, and deferred implementation work.",
    "- Confidence: High only when context scan/design QA passed and no critical ambiguity remains; otherwise stop with a concrete blocker.",
  ].filter(Boolean).join("\n");
}
